# GitHub Pages Jekyll Configuration
title: "Georg Fischer WMS Wissensdatenbank"
description: "Umfassende Warehouse Management System Wissensdatenbank für Georg Fischer"
baseurl: "/gfwms"
url: "https://zenilify.github.io"

# GitHub Integration
github:
  repository_nwo: "zenilify/gfwms"
  repository_url: "https://github.com/zenilify/gfwms"
  owner_name: "zenilify"
  owner_url: "https://github.com/zenilify"
  owner_gravatar_url: "https://github.com/zenilify.png"
  edit_page: true
  source:
    branch: "main"
    path: "/"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
navigation:
  - name: "Home"
    url: "/"
  - name: "Training"
    url: "/pages/training/"
  - name: "Wiki"
    url: "/pages/wiki/"
  - name: "Chatbot"
    url: "/pages/chatbot/"
  - name: "Error Docs"
    url: "/pages/errors/"

# SEO & Social
author:
  name: "Erick Hernandez Zenil"
  email: "erick@zenilify.com"
  github: "zenilify"
  url: "https://github.com/zenilify"
social:
  name: "Erick Hernandez Zenil"
  links:
    - "https://github.com/zenilify"
    - "https://zenilify.com"
twitter:
  username: "zenilify"
  card: summary_large_image

# Collections
collections:
  training:
    output: true
    permalink: /:collection/:name/
  wiki:
    output: true
    permalink: /:collection/:name/
  errors:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "training"
    values:
      layout: "training"
  - scope:
      path: ""
      type: "wiki"
    values:
      layout: "wiki"
  - scope:
      path: ""
      type: "errors"
    values:
      layout: "error"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
